---
-
  name: Install amavis and dependencies
  yum: name={{ item }} state=present
  with_items:
    - amavisd-new
    - clamav
    - clamav-devel
    - clamd
    - spamassassin
-
  name: add clam user to amavis group
  command: gpasswd -a clam amavis
-
  name: set start level for amavisd-new
  command: chkconfig --level 2345 amavisd on
-
  name: set start level for  clamd.amavisd
  command: chkconfig --level 2345 clamd.amavisd on
# -
#   name: set start level for spamassassin
#   command: chkconfig --level 2345 spamassassin
-
  name: start amavisd, spamassassin and clamd.amavisd as service
  service: name={{ item }} state=started
  with_items:
    - amavisd
    - clamd.amavisd
    # - spamassassin # no need because it is called by postfix
-
  name: create mysql user for amavis
  mysql_user: name=amavis
              host={{ item }}
              password=amavis priv=*.*:ALL,GRANT
              login_user=root
              login_password=
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
-
  name: create amavis database
  mysql_db: name={{ item }}
            state=present
  with_items:
    - amavis
