---
-
  name: remove port 80 entry
  tags: port
  lineinfile: dest=/etc/sysconfig/iptables
              regexp='--dport\ 80'
              state=absent
-
  name: insert port 80 entry
  tags: port
  lineinfile: dest=/etc/sysconfig/iptables
            line='-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'
            insertbefore='-A INPUT -i lo -j ACCEPT'
            state=present
  notify: restart iptables
-
  name: install apache if not present
  yum: name=httpd state=present

-
  name: make sure apache is running
  service: name=httpd state=started enabled=true

-
  name: check if virtual_hosts directory exists
  file: path=/etc/httpd/conf.d/virtual_hosts state=directory

-
  name: create /var/www/sites
  file: path=/var/www/sites
        state=directory
        owner=apache
        group=apache
-
  name: copy apache's main configuration file
  tags: apache_config
  template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify: restart apache

-
  name: copy nosendfile.conf
  when: env == 'local'
  copy: src=nosendfile.conf dest=/etc/httpd/conf.d/nosendfile.conf
  notify: restart apache
- include: php.yml
