---
-
  name: install MySQL
  yum: name={{ item }} state=present
  with_items:
    - MySQL-python
    - mysql-server

-
  name: make sure mysqld is running
  service: name=mysqld state=started enabled=true
-
  file: path=/etc/mysql/conf.d state=directory
# - name: Set MySQL number of connections
#   copy: src=/vagrant/ansible/templates/max_connections.cnf dest=/etc/mysql/conf.d/max_connections.cnf
#   notify: restart mysql
-
  name: Install mysql command line client configuration file
  template: src=/vagrant/ansible/templates/my.cnf dest=/home/vagrant/.my.cnf owner=vagrant group=vagrant
